#ifndef JETSTREAM_DOMAINS_CORE_SLICE_BLOCK_HH
#define JETSTREAM_DOMAINS_CORE_SLICE_BLOCK_HH

#include <string>

#include "jetstream/block.hh"

namespace Jetstream::Blocks {

struct Slice : public Block::Config {
    std::string slice = "[...]";
    bool contiguous = false;

    JST_BLOCK_TYPE(slice);
    JST_BLOCK_DOMAIN("Core");
    JST_BLOCK_PARAMS(slice, contiguous);
    JST_BLOCK_DESCRIPTION(
        "Slice",
        "Extracts a subset of a tensor.",
        "# Slice\n"
        "\n"
        "Keeps part of a tensor chosen with NumPy-style indices, such as one batch, one"
        " head, or a range of samples. It usually follows a batched source or a "
        "multi-head Filter, to send one part to the next block.\n"
        "\n"
        "- **An index removes its axis.** A single number drops that axis and its role,"
        " while a range keeps both.\n"
        "- **The output is a view by default.** Turn on Contiguous for blocks that "
        "reject strided buffers.\n"
        "- **A step does not change the sample rate.** Keeping every other sample still"
        " reports the source `sampleRate`.\n"
        "\n"
        "## Ports\n"
        "\n"
        "| Port | Type | Shape |\n"
        "|---|---|---|\n"
        "| **Input** (in) | Any type | Any shape. Strided input is accepted. |\n"
        "| **Output** (out) | Same as the input | The selected part. Indexed axes lose "
        "their role, and every other axis and attribute is kept. |\n"
        "\n"
        "## Settings\n"
        "\n"
        "| Setting | Default | Range | Effect |\n"
        "|---|---|---|---|\n"
        "| **Slice** | [...] | Entries in brackets, see Reference | Part of each axis "
        "to keep, outermost axis first. |\n"
        "| **Contiguous** | Off | On, Off | Copies the selection into a new contiguous "
        "buffer every cycle. |\n"
        "\n"
        "## Recipes\n"
        "\n"
        "| Goal | Settings | Input | Output |\n"
        "|---|---|---|---|\n"
        "| One batch | [0, ...] | 8 batches x 8,192 samples | 8,192 samples |\n"
        "| One head of a Filter | [1, ...] | 3 heads x 819 samples | 819 samples, ready"
        " for a Wideband FM Demodulator |\n"
        "| Half of each batch | [:, 0:4096] | 8 batches x 8,192 samples | 8 batches x "
        "4,096 samples, strided |\n"
        "| Every other sample | [::2], Contiguous on | 8,192 samples at 2 MS/s | 4,096 "
        "samples in a new buffer, still labeled 2 MS/s |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| The block reports an invalid slice syntax | A missing bracket, an empty "
        "entry, a negative number, or a space inside an entry | Write entries such as "
        "0, 2:10, or ::2, separated by commas inside brackets. |\n"
        "| The block reports that a slice index exceeds the dimensions or is out of "
        "range | An index or range end is past the axis size, or there are more entries"
        " than axes | Keep each entry within its axis, and use ... for axes you do not "
        "name. |\n"
        "| A block downstream reports that it expects a contiguous tensor | The "
        "selection is strided, such as a range on an inner axis or a step | Turn on "
        "Contiguous. |\n"
        "| A block downstream reports that its input size is zero | A range ends at or "
        "before its start, such as 5:2 | Make the end larger than the start. |\n"
        "| Frequencies downstream are off after a step | The `sampleRate` attribute "
        "still holds the source rate | Use a Decimator with Subsample, which updates "
        "the rate. |\n"
        "\n"
        "## Reference\n"
        "\n"
        "Entries are separated by commas and apply to the axes from the outermost, and "
        "axes after the last entry are kept whole.\n"
        "\n"
        "| Entry | Meaning |\n"
        "|---|---|\n"
        "| **n** | Index n alone, and removes the axis. |\n"
        "| **start:end** | Indices from start up to, not including, end. Either one is "
        "optional. |\n"
        "| **start:end:step** | Every step-th index of the range. Step is above 0. |\n"
        "| **:** | The whole axis. |\n"
        "| **...** | Every axis not named, at most once. Empty brackets mean the same. "
        "|\n"
        "\n"
        "Unlike NumPy, negative numbers and an empty step such as 1:5: are rejected, "
        "and an end past the axis size or more entries than axes is an error.\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "The block only changes the offset, shape, and strides that describe the input,"
        " so no values move and nothing is computed per buffer. Contiguous adds a copy "
        "into a new buffer on the same device. The model below covers valid entries for"
        " one buffer.\n"
        "\n"
        "```python\n"
        "import numpy as np\n"
        "\n"
        "def entry(text):\n"
        "    if text == \"...\":\n"
        "        return Ellipsis\n"
        "    if \":\" not in text:\n"
        "        return int(text)\n"
        "    return slice(*[int(v) if v else None for v in text.split(\":\")])\n"
        "\n"
        "def slice_tensor(x, slice_=\"[...]\", contiguous=False):\n"
        "    entries = [t.strip() for t in slice_[1:-1].split(\",\") if t.strip()]\n"
        "    y = x[tuple(entry(t) for t in entries)]\n"
        "    return np.ascontiguousarray(y) if contiguous else y\n"
        "```\n"
        "\n"
        "## See Also\n"
        "\n"
        "- **Filter** produces the heads it often picks from.\n"
        "- **Decimator** keeps every Nth sample and updates the rate.\n"
        "- **Reshape** regroups values instead of selecting them.\n"
        "- **Squeeze Dims** removes a size-one axis without indexing."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_CORE_SLICE_BLOCK_HH
