#ifndef JETSTREAM_DOMAINS_DSP_ADSB_BLOCK_HH
#define JETSTREAM_DOMAINS_DSP_ADSB_BLOCK_HH

#include "jetstream/block.hh"

namespace Jetstream::Blocks {

struct Adsb : public Block::Config {
    JST_BLOCK_TYPE(adsb);
    JST_BLOCK_DOMAIN("DSP");
    JST_BLOCK_NODE_SIZE(XL);
    JST_BLOCK_PARAMS();
    JST_BLOCK_DESCRIPTION(
        "ADS-B Decoder",
        "Decodes ADS-B Mode S frames and maps aircraft positions.",
        "# ADS-B Decoder\n"
        "\n"
        "Decodes aircraft transponder messages from raw radio samples and plots each "
        "aircraft on a world map with its recent track. It usually follows a Soapy SDR "
        "tuned to 1,090 MHz at a 2 MHz sample rate.\n"
        "\n"
        "- **The input must be 2 MS/s.** Set the source to 1,090 MHz with a Sample Rate"
        " of 2 MHz.\n"
        "- **Map labels use short units.** Labels give hundreds of feet and tens of "
        "knots, so 080 24 is 8,000 ft at 240 kt.\n"
        "- **Old positions fade out.** A target turns amber and shows STALE 15 seconds "
        "after its last position, and leaves after 120 seconds.\n"
        "- **Controls work in a detached window.** Click the expand icon on the view to"
        " open it.\n"
        "\n"
        "## Ports\n"
        "\n"
        "| Port | Type | Shape |\n"
        "|---|---|---|\n"
        "| **Input** (in) | CF32 | Needs a contiguous buffer with a `sampleAxis`, "
        "implied for one-dimensional input, and at least 240 samples. A `batchAxis` is "
        "read in order as one stream, and no other axis is allowed. A `sampleRate`, "
        "when set, must be 2 MHz. |\n"
        "\n"
        "## Readouts\n"
        "\n"
        "| Readout | Shows |\n"
        "|---|---|\n"
        "| **Aircraft** | One row per aircraft heard since the block started, with "
        "ICAO, Callsign, Alt (ft), Speed (kt), Hdg, Lat, and Lon. Missing values show a"
        " dash. |\n"
        "\n"
        "## Recipes\n"
        "\n"
        "All rows assume a Soapy SDR at Frequency 1,090 MHz and Sample Rate 2 MHz, "
        "except the last.\n"
        "\n"
        "| Goal | Settings | Input | Output |\n"
        "|---|---|---|---|\n"
        "| Track aircraft | Soapy SDR defaults | 8 batches x 8,192 complex samples at 2"
        " MS/s | 32.8 ms of air per buffer, with 0.4% of frames missed at buffer edges "
        "|\n"
        "| Fewer missed frames | Soapy SDR with Samples 32,768 | 8 batches x 32,768 "
        "complex samples at 2 MS/s | 131 ms of air per buffer, with 0.1% of frames "
        "missed |\n"
        "| Low latency | Soapy SDR with Batches 1, Samples 2,048 | 2,048 complex "
        "samples at 2 MS/s | 1 ms of air per buffer, with about 12% of frames missed |\n"
        "| Recorded capture | File Reader with Batch Size 262,144 | 262,144 complex "
        "samples with no `sampleRate` | Decoded as 2 MS/s, since a missing rate is not "
        "checked |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| The block reports that the input sample rate must be 2 MHz | The source runs"
        " at another rate, such as 2.4 MHz | Set Sample Rate in the source to 2 MHz. |\n"
        "| The map and the Aircraft table stay empty | The source is not tuned to 1,090"
        " MHz, which the block does not check, or the antenna hears no aircraft | Set "
        "Frequency to 1,090 MHz and place the antenna with a clear view of the sky. |\n"
        "| An aircraft is in the table but not on the map | No even and odd position "
        "frames arrived within 10 seconds of each other | Wait for more frames, or "
        "improve reception. |\n"
        "| The block reports an unsupported input data type | The input is not CF32 | "
        "Feed it the radio samples directly, or convert them with a Cast block. |\n"
        "| The block reports that channel inputs are not supported | The input has a "
        "`channelAxis`, such as the output of a multi-head Filter | Feed it the radio "
        "output directly. |\n"
        "\n"
        "## Controls\n"
        "\n"
        "| Action | Input |\n"
        "|---|---|\n"
        "| Zoom the map around the cursor | Scroll |\n"
        "| Pan the map | Drag |\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "Each buffer becomes a magnitude stream that libmodes scans for transponder "
        "frames, checking each CRC and repairing single-bit errors. Callsign, altitude,"
        " velocity, and position come from extended squitters, and a position needs an "
        "even and an odd frame close together in time. Frames that straddle two buffers"
        " are missed.\n"
        "\n"
        "## See Also\n"
        "\n"
        "- **Soapy SDR** receives the band it decodes.\n"
        "- **Spectrum Analyzer** shows the transponder bursts on the band.\n"
        "- **File Reader** replays a recorded capture."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_DSP_ADSB_BLOCK_HH
