FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update --fix-missing

#
# [NEW DEPENDENCY HOOK]
# This is copy-pasta from the README.md file.
# Update this as the README.md file changes.
#

RUN apt install -y git build-essential cmake pkg-config ninja-build meson git zenity
RUN apt install -y spirv-cross glslang-tools libglfw3-dev
RUN apt install -y mesa-vulkan-drivers libvulkan-dev vulkan-validationlayers
RUN apt install -y libsoapysdr-dev soapysdr-module-rtlsdr
RUN apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav 
RUN apt install -y python3-yaml

###

COPY . /cyberether
WORKDIR /cyberether

RUN git submodule update --init --recursive

RUN rm -fr build
RUN meson build -Dprefix=/usr
RUN cd build && ninja install

RUN rm -fr build-static
RUN meson build-static --default-library=static -Dprefix=/usr
RUN cd build-static && ninja

WORKDIR /