FROM archlinux:latest

#
# Built spirv-cross from source.
# Because YAY is not available in the base image.
# And it's a pain to install YAY inside a Docker container.
# This is more complicated than it needs to be.
#

RUN pacman -Syu --noconfirm git base-devel cmake pkg-config
RUN git clone https://github.com/KhronosGroup/SPIRV-Cross.git
RUN cd SPIRV-Cross && mkdir build && cd build && cmake .. && make -j && make install

##

#
# This is copy-pasta from the README.md file.
# Update this as the README.md file changes.
#

RUN pacman -Sy --noconfirm git base-devel cmake pkg-config ninja meson git zenity
RUN pacman -Sy --noconfirm glslang glfw-x11
RUN pacman -Sy --noconfirm vulkan-icd-loader vulkan-validation-layers
RUN pacman -Sy --noconfirm soapysdr soapyrtlsdr
RUN pacman -Sy --noconfirm gstreamer gst-plugins-base gst-plugins-good gst-libav

###

COPY . /cyberether
WORKDIR /cyberether

RUN rm -fr build
RUN git submodule update --init --recursive
RUN meson build -Dprefix=/usr
RUN cd build && ninja install

# Clean up
RUN pacman -Scc --noconfirm

WORKDIR /