FROM archlinux:latest

#
# Built spirv-cross from source.
# Because YAY is not available in the base image.
# And it's a pain to install YAY inside a Docker container.
# This is more complicated than it needs to be.
#

RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm git cmake pkg-config gcc make
RUN git clone https://github.com/KhronosGroup/SPIRV-Cross.git
RUN cd SPIRV-Cross && mkdir build && cd build && cmake .. && make -j && make install

##

#
# [NEW DEPENDENCY HOOK]
# This is copy-pasta from the README.md file.
# Update this as the README.md file changes.
#

RUN pacman -S --noconfirm git cmake pkg-config ninja meson git zenity
RUN pacman -S --noconfirm glslang glfw-wayland
RUN pacman -S --noconfirm vulkan-icd-loader vulkan-validation-layers
RUN pacman -S --noconfirm soapysdr soapyrtlsdr
RUN pacman -S --noconfirm gstreamer gst-plugins-base gst-plugins-good gst-libav
RUN pacman -S --noconfirm python-yaml
RUN pacman -S --noconfirm catch2

###

COPY . /cyberether
WORKDIR /cyberether

RUN git submodule update --init --recursive

RUN rm -fr build
RUN meson setup build -Dprefix=/usr
RUN cd build && ninja install

RUN rm -fr build-static
RUN meson setup build-static --default-library=static -Dprefix=/usr
RUN cd build-static && ninja

# Clean up
RUN pacman -Scc --noconfirm

WORKDIR /