#ifndef JETSTREAM_DOMAINS_DSP_FFT_BLOCK_HH
#define JETSTREAM_DOMAINS_DSP_FFT_BLOCK_HH

#include "jetstream/block.hh"

namespace Jetstream::Blocks {

struct Fft : public Block::Config {
    bool forward = true;
    bool complexOutput = false;

    JST_BLOCK_TYPE(fft);
    JST_BLOCK_DOMAIN("DSP");
    JST_BLOCK_PARAMS(forward, complexOutput);
    JST_BLOCK_DESCRIPTION(
        "FFT",
        "Performs the Fast Fourier Transform.",
        "# FFT\n"
        "\n"
        "Computes the discrete Fourier transform of each buffer along its sample axis, "
        "or the inverse transform. It usually sits between a radio source and an "
        "Amplitude block that turns the bins into decibels.\n"
        "\n"
        "- **The first bin is DC.** Negative frequencies fill the upper half of the "
        "output.\n"
        "- **Inverse is not normalized.** A forward and inverse round trip multiplies "
        "the signal by the sample axis length.\n"
        "- **Each lane is independent.** Every batch and channel is processed "
        "separately.\n"
        "\n"
        "## Ports\n"
        "\n"
        "| Port | Type | Shape |\n"
        "|---|---|---|\n"
        "| **Input** (in) | F32 or CF32 | Needs a `sampleAxis`, implied for "
        "one-dimensional input. A `batchAxis`, a `channelAxis`, and any other axis are "
        "transformed independently. |\n"
        "| **Output** (out) | Same as the input, or CF32 with Complex Output | Same "
        "shape, with every axis and attribute kept. Complex Output cuts the sample axis"
        " to floor(length / 2) + 1 bins. |\n"
        "\n"
        "## Settings\n"
        "\n"
        "| Setting | Default | Range | Effect |\n"
        "|---|---|---|---|\n"
        "| **Direction** | Forward | Forward, Inverse | Forward turns samples into "
        "bins, Inverse turns bins back into samples. |\n"
        "| **Complex Output** | Off | On, Off | Outputs complex bins from DC to half "
        "the rate instead of packed real values. Shown only for F32 input with Forward."
        " |\n"
        "\n"
        "## Recipes\n"
        "\n"
        "| Goal | Settings | Input | Output |\n"
        "|---|---|---|---|\n"
        "| Spectrum of radio samples | Defaults | 8,192 complex samples | 8,192 complex"
        " bins, DC first |\n"
        "| Half spectrum of a real signal | Complex Output on | 1,024 real samples | "
        "513 complex bins |\n"
        "| Packed real transform | Defaults | 1,024 real samples | 1,024 real values in"
        " packed order |\n"
        "| Back to samples | Inverse | 8,192 complex bins | 8,192 complex samples, "
        "scaled by 8,192 |\n"
        "| Batched spectra | Defaults | 8 batches x 1,024 complex samples | 8 batches x"
        " 1,024 complex bins |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| The block reports an unsupported input data type | The input is not F32 or "
        "CF32, such as CI16 samples from a file | Convert it with a Cast block. |\n"
        "| The block reports that the input needs valid signal axis metadata | A "
        "multi-dimensional input has no `sampleAxis` | Mark the axes with a Signal Axes"
        " block. |\n"
        "| The inverse output is far too large | The inverse does not divide by the "
        "sample axis length | Scale it by 1 / length with a Multiply Constant block. |\n"
        "| The center of the band shows at the left edge | Bins start at DC, and "
        "negative frequencies follow in the upper half | Put an Invert block before the"
        " FFT. |\n"
        "| Complex Output is missing | The input is CF32, or Direction is Inverse | "
        "Feed real input with Direction set to Forward. |\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "The block runs a one-dimensional transform along the sample axis, with no "
        "window and no scaling in either direction. Packed real values follow the "
        "FFTPACK order, the real part of the DC bin, then the real and imaginary parts "
        "of each later bin. The model below covers one buffer in every mode.\n"
        "\n"
        "```python\n"
        "import numpy as np\n"
        "\n"
        "def fft(x, forward=True, complex_output=False):\n"
        "    n = len(x)\n"
        "    if np.iscomplexobj(x):\n"
        "        return np.fft.fft(x) if forward else np.fft.ifft(x) * n\n"
        "    if not forward:\n"
        "        q = np.append(x[1:], 0)[:n // 2 * 2]\n"
        "        return np.fft.irfft(np.append(x[0], q[0::2] + 1j * q[1::2]), n) * n\n"
        "    spectrum = np.fft.rfft(x)\n"
        "    if complex_output:\n"
        "        return spectrum\n"
        "    pairs = np.column_stack((spectrum.real, spectrum.imag))[1:].ravel()\n"
        "    return np.append(spectrum[0].real, pairs)[:n]\n"
        "```\n"
        "\n"
        "## See Also\n"
        "\n"
        "- **Spectrum Engine** adds windowing and scaling for displays.\n"
        "- **Invert** centers DC when placed before it.\n"
        "- **Amplitude** turns the bins into decibels.\n"
        "- **Cast** converts integer samples to F32 or CF32."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_DSP_FFT_BLOCK_HH
