#ifndef JETSTREAM_DOMAINS_DSP_FILTER_ENGINE_BLOCK_HH
#define JETSTREAM_DOMAINS_DSP_FILTER_ENGINE_BLOCK_HH

#include "jetstream/block.hh"

namespace Jetstream::Blocks {

struct FilterEngine : public Block::Config {
    JST_BLOCK_TYPE(filter_engine);
    JST_BLOCK_DOMAIN("DSP");
    JST_BLOCK_NODE_SIZE(XS);
    JST_BLOCK_PARAMS();
    JST_BLOCK_DESCRIPTION(
        "Filter Engine",
        "Filters a signal using FIR filter coefficients.",
        "# Filter Engine\n"
        "\n"
        "Filters a signal with the coefficients on its Filter port, one channel per "
        "head, and decimates when the taps allow it. It usually pairs with a Filter "
        "Taps block after a radio source, and feeds demodulators.\n"
        "\n"
        "- **Two-dimensional taps add a channel axis.** Taps from Filter Taps add one, "
        "even for a single head.\n"
        "- **Decimates when the sizes allow.** Each channel then drops to the Bandwidth"
        " rate near 0 Hz, otherwise it stays at its offset.\n"
        "- **The rate comes from the taps.** The signal `sampleRate` is never read, so "
        "Filter Taps must match the source.\n"
        "- **Batches form one stream.** Each batch continues the previous one, and the "
        "filter tail carries into the next buffer.\n"
        "\n"
        "## Ports\n"
        "\n"
        "| Port | Type | Shape |\n"
        "|---|---|---|\n"
        "| **Signal** (in) | F32 or CF32 | Needs a `sampleAxis`, implied for "
        "one-dimensional input. A `batchAxis` is optional, and a `channelAxis` only "
        "works with one-dimensional taps. A complex signal must be contiguous. |\n"
        "| **Filter** (in) | F32 or CF32 | Taps on a `sampleAxis`, implied for one "
        "dimension, or heads x taps with `channelAxis` 0 and `sampleAxis` 1. At most "
        "the signal length plus one taps, contiguous when complex. Reads `sampleRate`, "
        "`bandwidth`, and `center` when present. |\n"
        "| **Output** (out) | CF32 | The signal shape, plus a `channelAxis` before the "
        "sample axis for two-dimensional taps. Decimation divides the sample axis and "
        "sets `sampleRate` to the Bandwidth. |\n"
        "\n"
        "## Recipes\n"
        "\n"
        "All rows assume a 2 MS/s source. Settings belong to the Filter Taps block on "
        "the Filter port, at its default Sample Rate of 2 MHz.\n"
        "\n"
        "| Goal | Settings | Input | Output |\n"
        "|---|---|---|---|\n"
        "| One FM station | Bandwidth 0.2 MHz, Center 0.4 MHz | 8,190 complex samples |"
        " 1 head x 819 samples at 200 kS/s |\n"
        "| Three FM stations | Heads 3, Bandwidth 0.2 MHz, Center 0, 0.4, -0.4 MHz | "
        "8,190 complex samples | 3 heads x 819 samples at 200 kS/s |\n"
        "| Batched capture | Bandwidth 0.25 MHz, Taps 97 | 4 batches x 8,192 complex "
        "samples | 4 batches x 1 head x 1,024 samples at 250 kS/s |\n"
        "| Filter only | Bandwidth 0.3 MHz | 8,192 complex samples | 1 head x 8,192 "
        "samples at 2 MS/s |\n"
        "| Custom taps | 31 real taps from a Python block, no attributes | 8,192 real "
        "samples | 8,192 complex samples at 2 MS/s |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| The log warns that resampling is bypassed | The taps lack their attributes, "
        "Sample Rate divided by Bandwidth is not whole, or the signal length or Taps "
        "minus one is not a multiple of it | Pick a Bandwidth that divides Sample Rate "
        "evenly, then adjust the buffer size or Taps, as in Batched capture. |\n"
        "| The log warns that the output is shifted by a small frequency | A Center "
        "does not fall on a bin of the transform, which spans the signal length plus "
        "Taps minus one | Move the center to a multiple of the bin size. |\n"
        "| The wrong signal comes out, or none at all | The Filter Taps Sample Rate "
        "does not match the source | Set Sample Rate in Filter Taps to the source rate."
        " |\n"
        "| The block reports that it cannot add filter channels to a signal with a "
        "channel axis | The signal has a `channelAxis` and the taps are two-dimensional"
        " | Pick one channel with a Slice block first. |\n"
        "| The block reports that it expects a contiguous tensor | The CF32 signal or "
        "CF32 taps are strided, such as a Slice with Contiguous off | Turn on "
        "Contiguous in the Slice. |\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "The block convolves by FFT overlap-add, with one forward transform of the "
        "signal shared by every head. Decimation folds the filtered spectrum before the"
        " inverse FFT, which matches mixing each channel down and dropping the extra "
        "samples. The model below covers one head and one buffer without the decimation"
        " conditions.\n"
        "\n"
        "```python\n"
        "import numpy as np\n"
        "\n"
        "def filter_engine(x, h, sample_rate=None, bandwidth=None, center=0.0):\n"
        "    y = np.convolve(np.asarray(x, complex), h)[:len(x)]\n"
        "    if sample_rate is None:\n"
        "        return y\n"
        "    bins = len(x) + len(h) - 1\n"
        "    k = center / sample_rate * bins\n"
        "    shift = np.sign(k) * np.floor(abs(k) + 0.5) / bins\n"
        "    down = np.exp(-2j * np.pi * shift * np.arange(len(y)))\n"
        "    return (y * down)[::int(sample_rate // bandwidth)]\n"
        "```\n"
        "\n"
        "## See Also\n"
        "\n"
        "- **Filter Taps** makes the bandpass taps it expects.\n"
        "- **Filter** combines both blocks in one.\n"
        "- **Slice** picks one head for single-channel blocks."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_DSP_FILTER_ENGINE_BLOCK_HH
