shader_pkg_lst += [{
    'name': 'signal_view',
    'shaders': [
        files(['signal.vert.glsl', 'signal.frag.glsl']),
        files(['fill.vert.glsl', 'fill.frag.glsl']),
        files(['waterfall.vert.glsl', 'waterfall.frag.glsl']),
        files(['mesh.vert.glsl', 'mesh.frag.glsl']),
        files(['frame.vert.glsl', 'frame.frag.glsl']),
        files(['trace.vert.glsl', 'trace.frag.glsl']),
        files(['skirt.vert.glsl', 'skirt.frag.glsl']),
    ],
    'kernels': [files(['waterfall_filter.comp'])],
}]
