# This is a cross compilation file to Emscripten (browser).

[binaries]
c = ['env', 'EMCC_FORCE_STDLIBS=libc,libclang_rt.builtins,libsockets', 'emcc']
cpp = ['env', 'EMCC_FORCE_STDLIBS=libc,libclang_rt.builtins,libsockets', 'em++']
ar = 'emar'
ranlib='emranlib'

[built-in options]
cpp_args = [
    # Optimization
    '-O3',
    '-flto',

    # Core build
    '-fPIC',
    '-fwasm-exceptions',
    '-sSUPPORT_LONGJMP=wasm',

    # Debugging / symbols
    '-gsource-map',

    # WebAssembly + Threading
    '-pthread',
    '-msimd128',

    # WebGPU
    '--use-port=emdawnwebgpu',
    '--use-port=contrib.glfw3:disableJoystick=true:disableMultiWindow=true:disableWebGL2=true']

cpp_link_args = [
    # Optimization
    '-O3',
    '-flto',

    # Core build
    '-fwasm-exceptions',
    '-s', 'SUPPORT_LONGJMP=wasm',

    # Debugging / symbols
    '-gsource-map']

c_args = cpp_args
c_link_args = cpp_link_args

default_library = 'static'

[properties]
main_module_link_args = [
    # Core build
    '--bind',
    '-s', 'MAIN_MODULE=1',

    # Debugging / symbols
    '--emit-symbol-map',

    # WebAssembly + Threading
    '-s', 'WASM=1',
    '-s', 'SHARED_MEMORY=1',
    '-s', 'ALLOW_MEMORY_GROWTH=1',
    '-s', 'ABORTING_MALLOC=1',
    '-s', 'PTHREAD_POOL_SIZE=4',
    '-s', 'PROXY_TO_PTHREAD=1',
    '-s', 'OFFSCREENCANVAS_SUPPORT=1',

    # Runtime
    '-s', 'STACK_SIZE=32MB',
    '-s', 'INITIAL_MEMORY=128MB',
    '-s', 'ERROR_ON_UNDEFINED_SYMBOLS=0',

    # Runtime behavior
    '-s', 'INVOKE_RUN=0',
    '-s', 'INCOMING_MODULE_JS_API=["ENVIRONMENT","arguments","canvas","dynamicLibraries","elementPointerLock","instantiateWasm","locateFile","monitorRunDependencies","noExitRuntime","noInitialRun","onAbort","onExit","onRuntimeInitialized","postRun","preInit","preRun","print","printErr","setStatus","statusMessage","stderr","stdin","stdout","thisProgram","wasm","wasmBinary","websocket"]',
    '-s', 'EXPORTED_RUNTIME_METHODS=["callMain", "HEAP8"]',
    '-s', 'MODULARIZE=1',
    '-s', 'EXPORT_ES6=1',
    '-s', 'EXIT_RUNTIME=1',

    # Assertions
    '-s', 'ASSERTIONS=1',

    # Filesystem
    '-sWASMFS',

    # WebGPU
    '--use-port=emdawnwebgpu',
    '--use-port=contrib.glfw3:disableJoystick=true:disableMultiWindow=true:disableWebGL2=true',

    # WebSocket
    '-lwebsocket.js',

    # Compression.
    '-sUSE_BZIP2=1']

side_module_link_args = [
    '-s', 'SIDE_MODULE=1',
    '-pthread']

[host_machine]
cpu = 'wasm'
cpu_family = 'wasm32'
endian = 'little'
system = 'emscripten'
