#ifndef JETSTREAM_DOMAINS_CORE_PYTHON_BLOCK_HH
#define JETSTREAM_DOMAINS_CORE_PYTHON_BLOCK_HH

#include <string>
#include <vector>

#include "jetstream/block.hh"
#include "jetstream/domains/core/python/module.hh"

namespace Jetstream::Blocks {

struct Python : public Block::Config {
    std::string source = "editor";
    std::string code = R"PY(def compute(ctx):
    ctx.outputs[0][...] = ctx.inputs[0]
    )PY";
    std::string file;
    U64 inputCount = 1;
    U64 outputCount = 1;
    std::vector<Modules::Python::TensorSpec> outputTensorSpecs;
    bool throttled = false;

    JST_BLOCK_TYPE(python);
    JST_BLOCK_DOMAIN("Core");
    JST_BLOCK_NODE_SIZE(XL);
    JST_BLOCK_PARAMS(source, code, file, inputCount, outputCount,
                     outputTensorSpecs, throttled);
    JST_BLOCK_DESCRIPTION(
        "Python",
        "Runs custom Python compute code.",
        "# Python\n"
        "\n"
        "Runs your own Python function once per cycle, on tensors shared with NumPy or "
        "CuPy without copies. It fits anywhere in a chain, to prototype a step before "
        "writing a native block or to glue blocks with NumPy, CuPy, and SciPy.\n"
        "\n"
        "- **Each output has a fixed spec.** The default is one F32 value, so set "
        "Output 0 before writing a buffer.\n"
        "- **Attributes are not copied to outputs.** Copy `sampleRate` and the rest "
        "from the input attributes in code.\n"
        "- **An exception stops the block.** It stays skipped until the code is "
        "reloaded or the block is recreated.\n"
        "\n"
        "## Ports\n"
        "\n"
        "| Port | Type | Shape |\n"
        "|---|---|---|\n"
        "| **Input 0** (in) | F32, F64, CF32, CF64, or an integer type from I8 to U64 |"
        " Any shape and strides, on the CPU or CUDA. One port per Input Count. |\n"
        "| **Output 0** (out) | Set by its spec | Shape, device, and axes from its "
        "spec. One port per Output Count. |\n"
        "\n"
        "## Settings\n"
        "\n"
        "| Setting | Default | Range | Effect |\n"
        "|---|---|---|---|\n"
        "| **Source** | Code Editor | Code Editor, File | Where the code comes from. |\n"
        "| **File** | Empty | A .py file | Script to run, with its console below. File "
        "only. |\n"
        "| **Code** | Copies Input 0 to Output 0 | Python defining `compute(ctx)` | "
        "Script to run. Code Editor only. |\n"
        "| **Input Count** | 1 | 0 to 64 | Input ports, from Input 0. |\n"
        "| **Output Count** | 1 | 0 to 64 | Output ports, from Output 0. |\n"
        "| **Throttled** | Off | On, Off | Runs compute at most 10 times per second and"
        " skips the cycles between. |\n"
        "| **Output 0** | Shape [1], F32, CPU, no axes | Any shape, a type from Ports, "
        "CPU or CUDA | Fixed shape, type, device, and signal axes of the output. One "
        "per output. |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| The console says an array cannot be broadcast into shape (1,) | Output 0 "
        "still has its default spec of one F32 value | Set its shape and type to match "
        "what compute writes. |\n"
        "| The output stops after an exception | A failing compute skips the block "
        "until the code reloads | Fix the code, or pick Reload Block from the node menu"
        " for a file. |\n"
        "| A block downstream reports that the signal is missing `sampleAxis` metadata "
        "| A multi-dimensional output declares no axes | Declare them in its spec, as "
        "in Declare Output Axes. |\n"
        "| Blocks downstream show the wrong rate, or report that the sample rate must "
        "be F32 | Output attributes start empty, and a plain float is stored as F64 | "
        "Copy the input attributes and wrap rates in `np.float32`, as in Pass "
        "Attributes Along. |\n"
        "| An import fails | The block runs a different Python than the terminal, or "
        "the package is missing | Pick the runtime under Settings, Runtime, Python "
        "Runtime, or declare the package as in Use Packages. |\n"
        "\n"
        "## Reference\n"
        "\n"
        "### Read Inputs and Write Outputs\n"
        "\n"
        "Define `compute(ctx)` and fill each output in place from the inputs, as below."
        " The block calls it once per cycle, the inputs are read-only, and module "
        "globals persist between calls. Arrays are NumPy on the CPU and CuPy on CUDA.\n"
        "\n"
        "```python\n"
        "def compute(ctx):\n"
        "    ctx.outputs[0][...] = ctx.inputs[0] * 2.0\n"
        "```\n"
        "\n"
        "### Pass Attributes Along\n"
        "\n"
        "Copy the attributes from the input and change what the script alters, as "
        "below, since outputs start with none. Wrap numbers in NumPy types, because a "
        "plain float is stored as F64 and most blocks expect an F32 `sampleRate`.\n"
        "\n"
        "```python\n"
        "import numpy as np\n"
        "\n"
        "def compute(ctx):\n"
        "    rate = ctx.input_attrs[0][\"sampleRate\"]\n"
        "    ctx.outputs[0][...] = ctx.inputs[0][::2]\n"
        "    ctx.output_attrs[0].update(ctx.input_attrs[0])\n"
        "    ctx.output_attrs[0][\"sampleRate\"] = np.float32(rate / 2)\n"
        "```\n"
        "\n"
        "### Declare Output Axes\n"
        "\n"
        "Write one role per axis in brackets next to the shape in the output spec, such"
        " as `[B, S]`, from the outermost, with `B` for batch, `C` for channel, `S` for"
        " sample, and `_` for none. Trailing axes without a role can be left out. "
        "Blocks downstream check axes before the first cycle, so they cannot be set in "
        "code.\n"
        "\n"
        "### Share Values With Other Blocks\n"
        "\n"
        "Write a dict under a top-level key of `ctx.env`, and read theirs the same way,"
        " as below. Every block and the Environment window see it.\n"
        "\n"
        "```python\n"
        "def compute(ctx):\n"
        "    gain = ctx.env.get(\"station\", {}).get(\"gain\", 1.0)\n"
        "    ctx.outputs[0][...] = ctx.inputs[0] * gain\n"
        "    ctx.env[\"status\"] = {\"peak\": float(abs(ctx.outputs[0]).max())}\n"
        "```\n"
        "\n"
        "### Read Metrics From Other Blocks\n"
        "\n"
        "Ask `ctx.metrics` for a metric by block name and metric name, as below, with a"
        " default for the first read, which only subscribes. Calling `subscribe_all()` "
        "follows every block at once. Each metric entry holds its `value`, `format`, "
        "`label`, and `help`.\n"
        "\n"
        "```python\n"
        "def compute(ctx):\n"
        "    progress = ctx.metrics.get_value(\"file_reader\", \"progress\", default=0.0)\n"
        "    ctx.metrics.subscribe_all()\n"
        "```\n"
        "\n"
        "### Skip a Cycle or Clean Up\n"
        "\n"
        "Return `SKIP` to skip a cycle, as below, and the blocks downstream skip it "
        "too. Define `cleanup()` to release resources when the block is destroyed or "
        "reloaded. Prints and exceptions go to the block console.\n"
        "\n"
        "```python\n"
        "def compute(ctx):\n"
        "    if abs(ctx.inputs[0]).max() < 0.1:\n"
        "        return SKIP\n"
        "    ctx.outputs[0][...] = ctx.inputs[0]\n"
        "```\n"
        "\n"
        "### Use Packages\n"
        "\n"
        "List the package in a PEP 723 header at the top of the code, as below. Missing"
        " packages are installed after approval, as set by Dependency Installation "
        "Policy under Settings, Runtime.\n"
        "\n"
        "```python\n"
        "# /// script\n"
        "# dependencies = [\"scipy~=1.14\"]\n"
        "# ///\n"
        "\n"
        "from scipy.signal import lfilter\n"
        "\n"
        "def compute(ctx):\n"
        "    ctx.outputs[0][...] = lfilter([0.5, 0.5], [1.0], ctx.inputs[0])\n"
        "```\n"
        "\n"
        "### Run on CUDA\n"
        "\n"
        "Set the output device to CUDA in its spec and synchronize before returning, as"
        " below, since CuPy runs its work asynchronously.\n"
        "\n"
        "```python\n"
        "import cupy as cp\n"
        "\n"
        "def compute(ctx):\n"
        "    ctx.outputs[0][...] = ctx.inputs[0] * 2.0\n"
        "    cp.cuda.Stream.null.synchronize()\n"
        "```\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "Every Python block shares one interpreter, so the dependencies declared by all"
        " blocks are resolved together. Tensors reach the code as views of the block "
        "memory, without copies.\n"
        "\n"
        "## See Also\n"
        "\n"
        "- The [Python Block guide](https://cyberether.org/docs/python-block) covers "
        "runtimes and dependencies.\n"
        "- Trained models run in the **ONNX Inference** block.\n"
        "- **Signal Axes** labels axes on any tensor."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_CORE_PYTHON_BLOCK_HH
