#ifndef JETSTREAM_DOMAINS_VISUALIZATION_NOTE_BLOCK_HH
#define JETSTREAM_DOMAINS_VISUALIZATION_NOTE_BLOCK_HH

#include "jetstream/block.hh"

namespace Jetstream::Blocks {

struct Note : public Block::Config {
    std::string content = "# Note\nWrite your **markdown** here.";

    JST_BLOCK_TYPE(note);
    JST_BLOCK_DOMAIN("Visualization");
    JST_BLOCK_NODE_SIZE(XL);
    JST_BLOCK_PARAMS(content);
    JST_BLOCK_DESCRIPTION(
        "Note",
        "Displays formatted markdown text inside a node.",
        "# Note\n"
        "\n"
        "Shows markdown text on the canvas, with live values from the flowgraph "
        "environment. It sits beside the blocks it explains, or next to a Python block "
        "that publishes status values.\n"
        "\n"
        "- **Changes apply only on Done.** Edit shows the raw markdown, and Done "
        "renders it again.\n"
        "- **Live values come only from the environment.** Metrics and tensor "
        "attributes appear only after a Python block copies them there.\n"
        "- **Values refresh at most ten times per second.** Each refresh follows a "
        "write to the environment.\n"
        "\n"
        "## Settings\n"
        "\n"
        "| Setting | Default | Range | Effect |\n"
        "|---|---|---|---|\n"
        "| **Content** | A Note heading and one line | Markdown with live values, see "
        "Reference | Text shown on the node. |\n"
        "\n"
        "## Troubleshooting\n"
        "\n"
        "| Symptom | Cause | Fix |\n"
        "|---|---|---|\n"
        "| A live value shows -- | The key, field, or index is not in the environment "
        "yet | Compare the path with the keys in Flowgraph, Show Environment View. |\n"
        "| A live value shows its path as text | The path does not start with env, or "
        "the format does not fit the value type, such as .2f on an integer | Start the "
        "path with env, and match the format to the type, such as d for an integer. |\n"
        "| A live value in backticks shows its path as text | Inline code and code "
        "fences are never expanded, except a stats fence | Move it out of the code. |\n"
        "| A table ends with a row counting the rest | A repeated line stops after 500 "
        "entries | Show fewer entries with a range such as [0:50]. |\n"
        "| The log warns that an environment value must be a mapping | A Python block "
        "assigned a plain value to a top-level key | Assign a dict, such as "
        "`ctx.env[\"rx\"] = {\"snr\": snr}`. |\n"
        "\n"
        "## Reference\n"
        "\n"
        "### Show a Live Value\n"
        "\n"
        "Write the path of the value inside `${ }`, as below. The note updates the "
        "value when it changes. A number in brackets picks a list entry, counting from "
        "the end when negative, and a format after a colon sets how the value prints.\n"
        "\n"
        "```markdown\n"
        "SNR **${env.receiver.snr:.1f} dB**, last station ${env.stations.list[-1].name}\n"
        "```\n"
        "\n"
        "### Build a Table From a List\n"
        "\n"
        "Write one table row with `[*]` in place of the list index, as below, and the "
        "row repeats for every entry. A range in the brackets limits the rows, and "
        "`._key` shows the name or index of each entry.\n"
        "\n"
        "```markdown\n"
        "| Station | Freq (MHz) |\n"
        "|---|---:|\n"
        "| ${env.stations.list[*].name} | ${env.stations.list[*].freq:.3f} |\n"
        "```\n"
        "\n"
        "### Show a Whole Map or List\n"
        "\n"
        "Write the path of the map or list without a field, as below. On its own line "
        "it becomes a table, or bullets for a plain list, and inside a sentence it "
        "becomes one line of up to 32 entries.\n"
        "\n"
        "```markdown\n"
        "${env.receiver}\n"
        "```\n"
        "\n"
        "### Show Stat Tiles\n"
        "\n"
        "Write one tile per line in a code fence tagged stats, as below, to get large "
        "numbers with small labels. Each line holds a label, a value, a color, and a "
        "caption, separated by bars, and only the value is required. The color is blue,"
        " green, purple, yellow, orange, or red, and a number after stats sets the "
        "columns.\n"
        "\n"
        "```text\n"
        "SNR | ${env.receiver.snr:.1f} dB | green\n"
        "Uptime | ${env.receiver.uptime:.0f} s\n"
        "```\n"
        "\n"
        "### Add a Callout\n"
        "\n"
        "Start a quote with the title in brackets, as below, to get a tinted box with "
        "that title. The titles are NOTE, TIP, IMPORTANT, WARNING, CAUTION, and ERROR.\n"
        "\n"
        "```markdown\n"
        "> [!WARNING]\n"
        "> Lower the gain before connecting the antenna.\n"
        "```\n"
        "\n"
        "### Show a Path as Plain Text\n"
        "\n"
        "Put a backslash before the dollar sign, as below, to show the path instead of "
        "its value.\n"
        "\n"
        "```markdown\n"
        "Type \\${env.receiver.snr} to show the SNR.\n"
        "```\n"
        "\n"
        "## Under the Hood\n"
        "\n"
        "The block holds only its text and creates no modules. The editor fills in each"
        " value and escapes it, so a value never changes the markdown around it.\n"
        "\n"
        "## See Also\n"
        "\n"
        "- The [Metadata guide](https://cyberether.org/docs/metadata) covers the "
        "flowgraph environment.\n"
        "- **Python** writes environment values through `ctx.env`."
    );
};

}  // namespace Jetstream::Blocks

#endif  // JETSTREAM_DOMAINS_VISUALIZATION_NOTE_BLOCK_HH
