name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    uses: ./.github/workflows/linux.yml

  windows:
    uses: ./.github/workflows/windows.yml

  macos:
    uses: ./.github/workflows/macos.yml

  emscripten:
    uses: ./.github/workflows/emscripten.yml

  containers:
    uses: ./.github/workflows/container.yml
