name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux-build:
    uses: ./.github/workflows/linux-build.yml

  windows-build:
    uses: ./.github/workflows/windows-build.yml

  macos:
    uses: ./.github/workflows/macos-build.yml

  emscripten:
    uses: ./.github/workflows/emscripten-build.yml
