name: Release

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    with:
      package_appimage: true

  wheel:
    uses: ./.github/workflows/wheel.yml

  windows:
    uses: ./.github/workflows/windows.yml
    with:
      package_msi: true

  macos:
    uses: ./.github/workflows/macos.yml
    with:
      package_dmg: true

  emscripten:
    uses: ./.github/workflows/emscripten.yml

  containers:
    uses: ./.github/workflows/container.yml
    permissions:
      contents: read
      packages: write
    with:
      publish: ${{ github.event_name == 'push' }}

  github-release:
    if: github.event_name == 'push'
    needs: [linux, wheel, windows, macos, emscripten]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'cyberether-bin-linux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'superluminal-wheel-manylinux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'cyberether-appimage-linux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-windows-x86_64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-msi-windows-x86_64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-macos-arm64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-dmg-macos-arm64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-emscripten-wasm32
          path: .dist/artifacts

      - name: Release
        uses: softprops/action-gh-release@v2.6.2
        with:
          files: |
            .dist/artifacts/*.tar.gz
            .dist/artifacts/*.dmg
            .dist/artifacts/*.AppImage
            .dist/artifacts/*.msi
