name: Release

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: read

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    with:
      package_desktop: true

  wheel:
    uses: ./.github/workflows/wheel.yml

  windows:
    uses: ./.github/workflows/windows.yml
    with:
      package_desktop: true

  macos:
    uses: ./.github/workflows/macos.yml
    with:
      package_desktop: true
    secrets: inherit

  emscripten:
    uses: ./.github/workflows/emscripten.yml

  containers:
    uses: ./.github/workflows/container.yml
    permissions:
      contents: read
      packages: write
    with:
      publish: ${{ github.event_name == 'push' }}

  github-release:
    if: github.event_name == 'push'
    needs: [linux, wheel, windows, macos, emscripten]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'cyberether-bin-linux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'superluminal-wheel-manylinux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          pattern: 'cyberether-release-linux-*'
          path: .dist/artifacts
          merge-multiple: true

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-windows-x86_64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-release-windows-x86_64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-macos-arm64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-release-macos-arm64
          path: .dist/artifacts

      - uses: actions/download-artifact@v4.3.0
        with:
          name: cyberether-bin-emscripten-wasm32
          path: .dist/artifacts

      - name: Upload release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$GITHUB_REF_NAME" \
            .dist/artifacts/* \
            --clobber \
            --repo "$GITHUB_REPOSITORY"

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit "$GITHUB_REF_NAME" --draft=false --repo "$GITHUB_REPOSITORY"
